name: calculator
description: >
  A simple and intuitive calculator app built using Flutter. 
  Supports basic arithmetic operations with a clean and responsive UI.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  math_expressions: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.3+1
  audioplayers: ^1.0.1
  path: ^1.8.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/tap.wav